services:
  shieldgate:
    image: shieldgate
    build: .
    container_name: shieldgate
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/config.yaml:/app/src/main/resources/config.yaml
    networks:
      - shield-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9095:9090"
    networks:
      - shield-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - shield-net

networks:
  shield-net:
    driver: bridge
